# # @package _global_

# defaults:
#   - _self_
#   - datamodule: mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
#   - model: mnist.yaml
#   - logger: null
#   - trainer: default.yaml
#   - paths: default.yaml
#   - extras: default.yaml
#   - hydra: default.yaml

# task_name: "eval"

# tags: ["dev"]

# # passing checkpoint path is necessary for evaluation
# ckpt_path: ???



defaults:
  - _self_
  - datamodule: cifar10.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: cifar10.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "logs/train/runs/2022-09-09_08-53-34/checkpoints/epoch_001.ckpt"
